// ----generate date data for .week-of-year div and .calender-container

var getThisWeek = function(date) {
  var firstDayThisYear = new Date(Date.parse('Jan 1, ' + date.getFullYear()));
  var daysFromFirstDay = Math.floor((today - firstDayThisYear) / 86400000);
  var weekNum = Math.floor((daysFromFirstDay + date.getDay() + 7*(firstDayThisYear.getDay()==0) - 1) / 7) + 1;
  return weekNum;
}

var today = new Date();
var thisYear = today.getFullYear();
var thisWeek = getThisWeek(today);
var thisDay = today.getDay();

$('#this-year-num').text(thisYear);
$('#this-week-num').text(thisWeek);

$('.date-in-week').each(function(index) {
  var weekNumTemp = new Date(today - 86400000 * (thisDay - index - 1 + 7*(thisDay === 0)));
  if (index == 5 || index == 6) {
    $(this).text((weekNumTemp.getMonth() + 1) + '.' + weekNumTemp.getDate());
  }
  else {
    $(this).text(weekNumTemp.getDate());
  }
});


// ----handle user's select of city

var theCity = $('#city-selected');
var cityList = $('#all-cities-container');
var cityContainer = $('#city-selected-container');
var cityItems = $('.city-item');

// default selectedCity is beijing
var selectedCity = 'beijing';

cityItems.each(function() {
  $(this).click(function() {
    $('#city-selected>span').text($(this).text());
    selectedCity = $(this).attr('id');
  });
});

$('.city-to-event').click(function() {
  $('.city-select-container').toggleClass('hide');
  $('.event-select-container').toggleClass('show');
});

/////////////////////

$('.event-to-city').click(function() {
  $('.city-select-container').toggleClass('hide');
  $('.event-select-container').toggleClass('show');
});


// ----handle user's select of event category

var eventCate = [];

$('.event-cate').each(function() {
  $(this).attr('addToCate', false);
  $(this).click(function() {
    if (eventCate.indexOf($(this).attr('id')) == -1) {
      if ($(this).attr('id') == 'all' && eventCate.length >= 1) {
        eventCate.splice(0, eventCate.length);
        $('.event-cate[addToCate="true"]').each(function() {
          $(this).attr('addToCate', false);
        });
      } else {
        if (eventCate.indexOf('all') !== -1) {
          eventCate.splice(eventCate.indexOf('all'), 1);
          $('#all').attr('addToCate', false);
        }
      };
      eventCate.push($(this).attr('id'));
      $(this).attr('addToCate', true);
    } else {
      $(this).attr('addToCate', false);
      eventCate.splice(eventCate.indexOf($(this).attr('id')), 1);
    };
    $('.event-cate').each(function() {
      if ($(this).attr('addToCate') == 'true') {
        $(this).addClass('cate-selected');
      }
      else {
        $(this).removeClass('cate-selected');
      }
    });
    console.log(eventCate);
  });
});


// `ajaxEventCate` is an array with the same length of `eventCate`. It is
// generated by ajaxCateGenerator() for functionality in launchDoubanAJAX().
var ajaxEventCate = [];

var ajaxCateGenerator = function(originalCate) {
  var ajaxCate = [];
  for (var i = 0; i < originalCate.length; i++) {
    ajaxCate[i] = new Object();
    ajaxCate[i].cateName = originalCate[i];
    ajaxCate[i].noMoreEvents = false;
    ajaxCate[i].dataAppended = false;
  }
  ajaxCate.requestNum = 0
  return ajaxCate;
}

// handle AJAX requests
var launchDoubanAJAX = function() {
  // turn off eventListener for scrollAndLoad temporarily when a AJAX request
  // is just sent
  $(window).off('scroll', scrollAndLoad);

  // see if user has selected a category
  if (ajaxEventCate.length) {
    for (var i = 0; i < ajaxEventCate.length; i++) {
      // fire AJAX request for each category that still has events on the server
      if (!ajaxEventCate[i].noMoreEvents) {
        // for each category, set prop `dataAppended` to false before getting
        // data back and successfully appending them to DOM
        ajaxEventCate[i].dataAppended = false;

        var eventURL = 'https://api.douban.com/v2/event/list?loc='
          + selectedCity + '&day_type=weekend&type=' + ajaxEventCate[i].cateName
          + '&start=' + 20 * ajaxEventCate.requestNum;
        $.ajax({
          url: eventURL,
          dataType: 'jsonp'
        }).done(function(data) {
          var allEventsParentNode = $('.all-events');
          console.log(data);
          // append events to `allEventsParentNode`
          for (var i = 0; i < data.events.length; i++) {
            var singleEventData = data.events[i];
            var eventCardNode = document.querySelector('#event-card-template');
            var eventImg = eventCardNode.content.querySelector('.event-img');
            var eventTitle = eventCardNode.content.querySelector('.event-title a');
            var eventTime = eventCardNode.content.querySelector('.event-time');
            var eventAddress = eventCardNode.content.querySelector('.event-address');
            var eventFee = eventCardNode.content.querySelector('.event-fee');
            eventImg.src = 'img/eventcard-backup.png';
            eventImg.src = singleEventData.image;
            eventTitle.textContent = singleEventData.title;
            eventTitle.href = singleEventData.url;
            eventTime.textContent = '时间：' + singleEventData.time_str;
            eventAddress.textContent = '地点：' + singleEventData.address;
            eventFee.textContent = '费用：' + singleEventData.fee_str;
            var cloneEventCard = document.importNode(eventCardNode.content, true);
            allEventsParentNode.append(cloneEventCard);
          };

          // when a set of data sent back from server, we have to get its category
          // because we allow user to choose more than one category
          for (var i = 0; i < ajaxEventCate.length; i++) {
            if (this.url.includes('type=' + ajaxEventCate[i].cateName)) {
              var thisCate = ajaxEventCate[i].cateName;
              var thisCateIndex = i;
              break;
            };
          };

          // set certain category's `dataAppended` to true
          ajaxEventCate[thisCateIndex].dataAppended = true;
          // check if there are still more events on the server for this certain
          // category
          if (data.total <= 20 * (ajaxEventCate.requestNum + 1)) {
            ajaxEventCate[thisCateIndex].noMoreEvents = true;
          };

          // check if all requests have their data sent back
          for (var i = 0; i < ajaxEventCate.length; i++) {
            if (!ajaxEventCate[i].dataAppended) {
              return;
            };
          };

          // if all requests have their data sent back, check if there are still
          // more events on the server for every category
          for (var i = 0; i < ajaxEventCate.length; i++) {
            if (!ajaxEventCate[i].noMoreEvents) {
              ajaxEventCate.requestNum++;
              // if there are still more events on the server for some category,
              // start listening to `scroll` events
              $(window).on('scroll', scrollAndLoad);
              return;
            };
          };

          // if (all requests have their data sent back, and) there are no more
          // events for all categories, inform the user
          var eventNotFoundMsg = (allEventsParentNode.children().length) ?
                '指定分类没有更多活动了哦' + '<br>' + '看看其他分类吧~' :
                '本周末没有指定分类的活动' + '<br>' + '换个分类试试吧~' ;
          $('.all-events').append('<p class="event-not-found-msg">' + eventNotFoundMsg + '</p>');
        });
      }
    };
  } else {
    // if no categories are selected, inform the iser
    $('.all-events').append('<p class="event-not-found-msg">' + '请先选定一个分类哦~' + '</p>');
  };
};

$('.event-to-list').click(function() {
  $('.calender-container').toggleClass('hide');
  $('.event-cate-container').toggleClass('tiles');
  $('.event-cate-filter').toggleClass('show-filter');
  $('.all-events').empty();
  ajaxEventCate = ajaxCateGenerator(eventCate);
  launchDoubanAJAX(ajaxEventCate.requestNum);
});

$('.event-cate-filter').click(function() {
  $('.all-events').empty();
  ajaxEventCate = ajaxCateGenerator(eventCate);
  launchDoubanAJAX(ajaxEventCate.requestNum);
})

var scrollAndLoad = function() {
  var contentHeightRemain = $(document).height() - $(this).scrollTop();
  if (contentHeightRemain <= $(this).innerHeight()*1.5) {
    launchDoubanAJAX(ajaxEventCate.requestNum);
  };
};


// window.addEventListener('scroll', function() {
//   var contentHeightRemain = document.documentElement.scrollHeight;
// }, false);
